name: wallpaper_fake_call
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  async_wallpaper: ^2.0.1
  camera: ^0.10.1
  cupertino_icons: ^1.0.2
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_ringtone_player: ^3.2.0
  get: 4.6.5
  google_mobile_ads: ^2.3.0
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  video_player: ^2.4.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/wallpapers/
